In [2]:
import numpy as np

# 1. Sample 6x6 grayscale image
image = np.array([
    [3, 0, 1, 2, 7, 4],
    [1, 5, 8, 9, 3, 1],
    [2, 7, 2, 5, 1, 3],
    [0, 1, 3, 1, 7, 8],
    [4, 2, 1, 6, 2, 8],
    [2, 4, 5, 2, 3, 9]
])

# 2. 3x3 Filter (Kernel)
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# 3. Convolution Operation
def convolve2d(image, kernel):
    output_dim = image.shape[0] - kernel.shape[0] + 1
    output = np.zeros((output_dim, output_dim))
    for i in range(output_dim):
        for j in range(output_dim):
            output[i][j] = np.sum(image[i:i+3, j:j+3] * kernel)
    return output

# 4. ReLU Activation
def relu(x):
    return np.maximum(0, x)

# 5. Max Pooling 2x2
def max_pooling(feature_map):
    output_dim = feature_map.shape[0] // 2
    output = np.zeros((output_dim, output_dim))
    for i in range(0, feature_map.shape[0], 2):
        for j in range(0, feature_map.shape[1], 2):
            output[i//2][j//2] = np.max(feature_map[i:i+2, j:j+2])
    return output

# 6. Fully Connected Layer (Dummy)
def fully_connected(x):
    weights = np.random.rand(x.size, 2)  # Let's say we classify into 2 classes
    x_flat = x.flatten()
    output = np.dot(x_flat, weights)
    return output

# 🚀 Run all steps
conv_output = convolve2d(image, kernel)
activated = relu(conv_output)
pooled = max_pooling(activated)
final_output = fully_connected(pooled)

# 🖨️ Show results
print("Original Image:\n", image)
print("\nAfter Convolution:\n", conv_output)
print("\nAfter ReLU:\n", activated)
print("\nAfter Max Pooling:\n", pooled)
print("\nFully Connected Output (Logits):\n", final_output)


Original Image:
 [[3 0 1 2 7 4]
 [1 5 8 9 3 1]
 [2 7 2 5 1 3]
 [0 1 3 1 7 8]
 [4 2 1 6 2 8]
 [2 4 5 2 3 9]]

After Convolution:
 [[ -5.  -4.   0.   8.]
 [-10.  -2.   2.   3.]
 [  0.  -2.  -4.  -7.]
 [ -3.  -2.  -3. -16.]]

After ReLU:
 [[0. 0. 0. 8.]
 [0. 0. 2. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

After Max Pooling:
 [[0. 8.]
 [0. 0.]]

Fully Connected Output (Logits):
 [2.65765792 3.68577631]
